import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // for pagination
import styles from './ui/home.module.css'
import HomeButton from './ui/homebutton';
import Joinbutton from './ui/joinbutton';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.headCont}>
          <HomeButton/>
          <div>
            <Joinbutton/>
          </div>
        </div>
        {children}
        </body>
    </html>
  );
}
