import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ChildrenProps } from "./ChildrenProps";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }: ChildrenProps) {
  return (
      <div className='flex flex-col justify-between h-screen w-screen overflow-hidden'>
        {children}
      </div>
  );
}
