import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from './component/homeBnt';
import Slide from './ui/silde';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='w-screen h-screen flex flex-col justify-between'>
        {children}
      </body>
    </html>
  );
}
